### ISSUE TITLE
Thanks for your great work! I made a mistake during training and would like to ask for advice.

### ISSUE THREAD

**Issue by flyxuexi** [cocowy1/ADStereo#1]
The following error occurred while running main.py. What is the reason?Thank you!

  File "/home/fly/stereo/adstereo/main.py", line 126, in train
    epe = torch.mean(torch.abs(outputs[-1][mask] - disp_true[mask]))
KeyError: -1

**Comment by cocowy1** [comment]
Could you paste the error details?

**Comment by flyxuexi** [comment]
> Could you paste the error details?

    #epe = torch.mean(torch.abs(outputs[-1][mask] - disp_true[mask]))

It is here in line 126 epe in mian.py. I replaced this line of code with finetune.py code, as shown below, so that main.py can work normally.May I ask if my actions are correct?

    epe = torch.mean(torch.abs(outputs["disp"][-1][mask] - disp_true[mask]))

**Comment by flyxuexi** [comment]
> Could you paste the error details?

Also, when refine=true, 6 items will be returned. Do you need to change the loss function? How can I change it? Thank you very much！

def model_loss(disp_ests, disp_gt, mask):
    weights = [0.5, 0.7, 1.0, 1.3, 1.6, ？]
    all_losses = []
    for disp_est, weight in zip(disp_ests, weights):
        all_losses.append(weight * F.smooth_l1_loss(disp_est[mask], disp_gt[mask], reduction='mean'))
    return sum(all_losses)

**Comment by cocowy1** [comment]
> > Could you paste the error details?
> 
> Also, when refine=true, 6 items will be returned. Do you need to change the loss function? How can I change it? Thank you very much！
> 
> def model_loss(disp_ests, disp_gt, mask): weights = [0.5, 0.7, 1.0, 1.3, 1.6, ？] all_losses = [] for disp_est, weight in zip(disp_ests, weights): all_losses.append(weight * F.smooth_l1_loss(disp_est[mask], disp_gt[mask], reduction='mean')) return sum(all_losses)

In my opinion, the choice of loss function coefficients—whether [0.5, 0.7, 1.0, 1.3, 1.6, 1.6] or [0.5, 0.7, 1.0, 1.3, 1.6, 2.0]—does not significantly impact the final performance.

**Comment by flyxuexi** [comment]
> It is here in line 126 epe in mian.py. I replaced this line of code with finetune.py code, as shown below, so that main.py can work normally.May I ask if my actions are correct?

got it,thanks! In addition, may I ask if my changes below are correct?

#epe = torch.mean(torch.abs(outputs[-1][mask] - disp_true[mask]))

It is here in line 126 epe in mian.py. I replaced this line of code with finetune.py code, as shown below, so that main.py can work normally.May I ask if my actions are correct?

epe = torch.mean(torch.abs(outputs["disp"][-1][mask] - disp_true[mask]))

**Comment by flyxuexi** [comment]
> It is here in line 126 epe in mian.py. I replaced this line of code with finetune.py code, as shown below, so that main.py can work normally.May I ask if my actions are correct?

got it,thanks! In addition, may I ask if my changes below are correct?

#epe = torch.mean(torch.abs(outputs[-1][mask] - disp_true[mask]))

It is here in line 126 epe in mian.py. I replaced this line of code with finetune.py code, as shown below, so that main.py can work normally.May I ask if my actions are correct?

epe = torch.mean(torch.abs(outputs["disp"][-1][mask] - disp_true[mask]))

**Comment by cocowy1** [comment]
> > It is here in line 126 epe in mian.py. I replaced this line of code with finetune.py code, as shown below, so that main.py can work normally.May I ask if my actions are correct?
> 
> got it,thanks! In addition, may I ask if my changes below are correct?
> 
> #epe = torch.mean(torch.abs(outputs[-1][mask] - disp_true[mask]))
> 
> It is here in line 126 epe in mian.py. I replaced this line of code with finetune.py code, as shown below, so that main.py can work normally.May I ask if my actions are correct?
> 
> epe = torch.mean(torch.abs(outputs["disp"][-1][mask] - disp_true[mask]))

Thanks, I have fixed this bug.
